In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({ "Order Date": [ "2024-01-10", "2024-01-15", "2024-02-05", "2024-02-12", "2024-03-01", "2024-03-15", "2024-04-10", "2024-04-20", "2024-05-05", "2024-01-15"     ],      "Product Name": [         "Laptop",         "Mouse",         "Printer",         "Tablet",         "Laptop",         "Monitor",         "Mouse",         "Printer",         "Smartwatch",         "Mouse"     ],      "Category": [         "Electronics",         "Accessories",         "Office",         "Electronics",         "Electronics",         "Accessories",         "Accessories",         "Office",         "Electronics",         "Accessories"     ],      "Region": [         "North",         "South",         "East",         "West",         "North",         "South",         "East",         "West",         "North",         "South"     ],      "Quantity": [         2,         5,         3,         4,         1,         2,         6,         2,         3,         5     ],      "Sales": [         50000,         2500,         9000,         30000,         55000,         16000,         3000,         6000,         45000,         2500     ],      "Profit": [         10000,         500,         1500,         6000,         11000,         3000,         None,         1000,         9000,         500     ] })

In [11]:
import pandas as pd

# Create your first dataframe
df = pd.DataFrame({
    "Order Date": ["2024-01-10", "2024-01-15"],
    "Sales": [50000, 2500]
})

# Create your second dataframe
new_sales = pd.DataFrame({
    "Order Date": ["2024-02-05", "2024-02-12"],
    "Sales": [9000, 30000]
})

# Combine them cleanly
combined_df = pd.concat([df, new_sales], ignore_index=True)

print("CONCATENATED DATA:")
display(combined_df)

CONCATENATED DATA:

   Order Date  Sales
0  2024-01-10  50000
1  2024-01-15   2500
2  2024-02-05   9000
3  2024-02-12  30000

In [12]:
print("NEW SALES DATA") 
display(new_sales) 
combined_df = pd.concat( [df, new_sales], ignore_index=True ) 
print("CONCATENATED DATA")
display(combined_df)

NEW SALES DATA

   Order Date  Sales
0  2024-02-05   9000
1  2024-02-12  30000

CONCATENATED DATA

   Order Date  Sales
0  2024-01-10  50000
1  2024-01-15   2500
2  2024-02-05   9000
3  2024-02-12  30000

In [14]:
import pandas as pd

# 1. Define df
df = pd.DataFrame({
    "Order Date": ["2024-01-10", "2024-01-15", "2024-02-05"],
    "Product Name": ["Laptop", "Mouse", "Printer"],
    "Sales": [50000, 2500, 9000]
})

# 2. Define product_info with the exact same Product Name column
product_info = pd.DataFrame({
    "Product Name": ["Laptop", "Mouse", "Printer"],
    "Discount": [10, 5, 15]
})

# 3. Merge them
merged_df = pd.merge(df, product_info, on="Product Name", how="left")

print("MERGED DATA:")
display(merged_df)

MERGED DATA:

   Order Date Product Name  Sales  Discount
0  2024-01-10       Laptop  50000        10
1  2024-01-15        Mouse   2500         5
2  2024-02-05      Printer   9000        15

In [15]:
product_info = pd.DataFrame({ "Product Name": [ "Laptop", "Mouse", "Printer", "Tablet", "Monitor" ], "Supplier": [ "Dell", "Logitech", "HP", "Samsung", "LG" ], "Discount": [ 10, 5, 15, 8, 12 ] }) 
print("PRODUCT INFORMATION") 
display(product_info)
merged_df = pd.merge( df, product_info, on="Product Name", how="left" ) 
print("MERGED DATA") 
display(merged_df)

PRODUCT INFORMATION

  Product Name  Supplier  Discount
0       Laptop      Dell        10
1        Mouse  Logitech         5
2      Printer        HP        15
3       Tablet   Samsung         8
4      Monitor        LG        12

MERGED DATA

   Order Date Product Name  Sales  Supplier  Discount
0  2024-01-10       Laptop  50000      Dell        10
1  2024-01-15        Mouse   2500  Logitech         5
2  2024-02-05      Printer   9000        HP        15

In [19]:
region_info = pd.DataFrame( {  "Region_Manager": [ "Manager A", "Manager B", "Manager C", "Manager D" ] },
                            index=[ "North", "South", "East", "West" ] ) 
print("REGION INFORMATION") 
display(region_info)
df_region = df.set_index("Region") 
joined_df = df_region.join(region_info)
print("JOINED DATA")
display(joined_df)

REGION INFORMATION

      Region_Manager
North      Manager A
South      Manager B
East       Manager C
West       Manager D

KeyError: "None of ['Region'] are in the columns"

In [25]:
import pandas as pd

# Define the dataframe directly to avoid file path errors
df = pd.DataFrame({
    "Order Date": ["2024-01-10", "2024-01-15", "2024-02-05", "2024-02-12"],
    "Region": ["North", "South", "East", "West"],
    "Sales": [50000, 2500, 9000, 30000]
})

region_sales = df.groupby("Region")["Sales"].sum()
print("TOTAL SALES BY REGION")
display(region_sales)

TOTAL SALES BY REGION

Region
East      9000
North    50000
South     2500
West     30000
Name: Sales, dtype: int64

In [27]:
import pandas as pd

# Define df with all required columns so pandas finds them
df = pd.DataFrame({
    "Category": ["Electronics", "Accessories", "Office", "Electronics"],
    "Region": ["North", "South", "East", "West"],
    "Sales": [50000, 2500, 9000, 30000]
})

pivot_table = pd.pivot_table(df, values="Sales", index="Category", columns="Region", aggfunc="sum", fill_value=0)
print("PIVOT TABLE")
display(pivot_table)

PIVOT TABLE

Region       East  North  South   West
Category
Accessories     0      0   2500      0
Electronics     0  50000      0  30000
Office       9000      0      0      0